### ISSUE TITLE
May I ask why the files in the folder are all 0KB?

### ISSUE THREAD

**Issue by qfotcom** [XinZhang525/CAC#1]

**Comment by XinZhang525** [comment]
That was because the codes were not downloaded to my laptop before I uploaded them to github. I have re-uploaded them.

**Comment by qfotcom** [comment]
Thank you for your contributions and dedication, and I appreciate your response as well.

**Comment by qfotcom** [comment]
Dear author,

Hello again! I apologize for bothering you once more. Thank you for the five datasets you provided earlier. While delving into the code, I couldn't locate the 'train_traj_unsuccess_month_07.pkl' file mentioned in file 'train.py.' Considering the latest datasets you provided, could you please guide me on where to find this file?

Thank you!








                       
原始邮件
                       
                     

发件人："XinZhang525"< ***@***.*** &gt;;

发件时间：2024/2/4 11:10

收件人："XinZhang525/CAC"< ***@***.*** &gt;;

抄送人："ChinaIIS"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [XinZhang525/CAC] May I ask why the files in the folder are all0KB? (Issue #1)




 
That was because the codes were not downloaded to my laptop before I uploaded them to github. I have re-uploaded them.
